In [1]:
import urllib
import time
import numpy as np
import pandas as pd

In [2]:
from urllib.request import urlopen
import time

In [3]:
from bs4 import BeautifulSoup

In [5]:
file = pd.read_excel(r'C:/Users/parks/Desktop/인턴_보고서/Modularity_class.xlsx')

In [6]:
file .set_index(file['Id'], inplace=True)
file.drop(['Id'], axis=1, inplace=True)

In [4]:
code = {'하나제약':'293480', '피델릭스':'032580', '크라운해태홀딩스':'005740', '퍼시스':'016800', '큐캐피탈':'016600',
       '인텔리인테크':'189300', '진양화학':'051630', '평화정공':'043370', '지투알':'035000', '파세코':'037070',
       '피제이메탈':'128660', '하이텍팜':'106190', '파인디엔씨':'049120', '성광벤드':'014620', '티엘아이':'062860',
       '특수건설':'026150', '하이트론':'019490', '토박스코리아':'215480'}

In [7]:
t1 = time.time()

sector_variationlist = []

for i in list(code.values()):
    stockCode = i
    variationlist = []

    dayPriceUrl = 'http://finance.naver.com/item/sise_day.nhn?code=' + stockCode
    dayPriceHtml = urlopen(dayPriceUrl)
    dayPriceSource = BeautifulSoup(dayPriceHtml.read(), "html.parser")

    dayPricePageNavigation = dayPriceSource.find_all("table", align="center")
    dayPriceMaxPageSection = dayPricePageNavigation[0].find_all("td", class_="pgRR")
    #dayPriceMaxPageNum = int(dayPriceMaxPageSection[0].a.get('href')[-3:])

    #for page in range(1, dayPriceMaxPageNum + 1) 하면 나와있는 끝까지

    for page in range(1, 100):
        url = 'http://finance.naver.com/item/sise_day.nhn?code=' + stockCode + '&page=' + str(page)
        html = urlopen(url)
        source = BeautifulSoup(html.read(), "html.parser")
        srlists = source.find_all("tr")
        isCheckNone = None

        # day: 날짜
        # closingPrice: 종가
        # variation: 전일대비
        # openingPrice: 시가
        # highestPrice: 고가
        # lowestPrice: 저가
        # volume: 거래량

        for i in range(1, len(srlists)-1):  
            if (srlists[i].span != isCheckNone):
                           
                variation = srlists[i].find_all('td', class_='num')[1].text.strip()
                openingPrice = srlists[i].find_all("td", class_="num")[2].text
                
                openingPrice2 = openingPrice.replace(',', '')
                variation2 = variation.replace(',', '')
                
                if float(openingPrice2) == 0:
                    pass
                else:
                    percent = float(variation2)/float(openingPrice2) * 100
                    variationlist.append(percent)


    a = np.array(variationlist)  
    sector_variationlist.append(a.mean())
     

t2 = time.time()

print('걸린 시간:', t2-t1)
print(sector_variationlist)

걸린 시간: 121.08494162559509
[4.960816686143502, 2.1286478203352575, 2.2588621492058123, 0.6934779975621513, 2.6127983557414836, 2.83584146498963, 2.087965392214047, 1.6925097227666301, 1.0964379833513398, 1.8808423971220278, 1.4712858616650377, 1.3829167271894611, 2.9223155556213465, 1.7950945689234603, 1.5720930811979337, 2.5959202433168334, 1.7713739560022144, 2.318943377527054]

In [ ]:
df2 = pd.read_excel(r'C:/Users/parks/Desktop/20190715_KOSPI200_list.xlsx') #KOSPI200 종목코드-이름 리스트 엑셀도 첨부
df2.drop(['Unnamed: 0'], axis=1, inplace=True)


for i in range(len(df2)):
    df2['code'][i] = df2['code'][i][1:]

name_dict = {}
for i in range(len(df2)):
    name_dict[df2['name'][i]] = df2['code'][i]

In [ ]:
name_list = []

for i in name_dict.keys():
    if i in list(file.index):
        name_list.append(i)

In [11]:
t1 = time.time()

kospi_variationlist = []

for i in name_list:
    stockCode = name_dict[i]
    variationlist = []

    dayPriceUrl = 'http://finance.naver.com/item/sise_day.nhn?code=' + stockCode
    dayPriceHtml = urlopen(dayPriceUrl)
    dayPriceSource = BeautifulSoup(dayPriceHtml.read(), "html.parser")

    dayPricePageNavigation = dayPriceSource.find_all("table", align="center")
    dayPriceMaxPageSection = dayPricePageNavigation[0].find_all("td", class_="pgRR")
    #dayPriceMaxPageNum = int(dayPriceMaxPageSection[0].a.get('href')[-3:])

    #for page in range(1, dayPriceMaxPageNum + 1) 하면 나와있는 끝까지

    for page in range(1, 100):
        url = 'http://finance.naver.com/item/sise_day.nhn?code=' + stockCode + '&page=' + str(page)
        html = urlopen(url)
        source = BeautifulSoup(html.read(), "html.parser")
        srlists = source.find_all("tr")
        isCheckNone = None

        for i in range(1, len(srlists)-1):  
            if (srlists[i].span != isCheckNone):
                           
                variation = srlists[i].find_all('td', class_='num')[1].text.strip()
                openingPrice = srlists[i].find_all("td", class_="num")[2].text
                
                openingPrice2 = openingPrice.replace(',', '')
                variation2 = variation.replace(',', '')
                
                if float(openingPrice2) == 0:
                    pass
                else:
                    percent = float(variation2)/float(openingPrice2) * 100
                    variationlist.append(percent)


    a = np.array(variationlist)  
    kospi_variationlist.append(a.mean())
     

t2 = time.time()

print('걸린 시간:', t2-t1)
print(kospi_variationlist)

걸린 시간: 958.8928818702698
[1.23885377338062, 1.7305689854266746, 1.3622935935397333, 1.5743553837961008, 1.9680066288278029, 1.0764755157857324, 1.0782528148118662, 1.5288669969254345, 1.6042357757331747, 2.9086501626325556, 1.4265534436002991, 1.1935376373359492, 1.3449694286415073, 1.2572548897337377, 1.6011389968529501, 1.7758570401979605, 1.1455451393784903, 1.4942583983743138, 1.2876620059178145, 1.189304973586246, 1.2676389683252478, 1.1078797603920951, 1.6101281239179157, 1.5820453540935462, 1.7203302373585665, 1.415145549287558, 1.5035309540705077, 1.732800512260103, 1.7419844840759495, 1.250107754788017, 2.401745472175412, 1.0861937324945399, 0.7592751817334865, 1.7787597816306175, 1.220903770962515, 1.5535447120405905, 1.6007146711567946, 1.538936323737243, 1.914638826064974, 1.1640659388576728, 1.917947947868223, 1.159089099794837, 1.3140676423681645, 1.1574121760584442, 1.507465450739262, 1.5492624401453954, 1.2235592224509444, 1.390693083795831, 1.3952123074203449, 1.5251468066799851, 1.2548981882571901, 2.794683382115814, 1.24843999530126, 2.4613203999679225, 7.901916415514293, 2.177744167177793, 1.3884915645621272, 1.605455132188588, 1.42275500816886, 2.069623475245112, 1.6435534555273794, 1.5068593124814404, 1.5204594891000167, 1.8188339937017726, 1.3424757743232754, 1.5335620335903966, 1.8570866678321223, 1.871777372490418, 1.9628361090462652, 1.836279848854801, 1.4368801700419735, 1.1741480441888332, 2.0248327775396002, 1.6200812175211046, 2.3068282428031655, 2.1231701563739462, 1.2811445539115225, 1.6863145823752907, 1.5481315511350116, 1.7342430983360484, 3.7126972745614513, 1.700986006033956, 1.1730327343185465, 1.3429104472967854, 1.3679992424053835, 1.5194383671876297, 1.4237166081086943, 1.6295211725979404, 1.3803611327081131, 1.9582652806046783, 1.2763375758966442, 2.0786995516234508, 1.688237990708057, 1.9576152778391136, 2.0640176436275466, 1.9087540739142579, 1.2273717071898917, 1.5709213636566985, 1.58036538626201, 1.750280795849569, 1.6316383476370198, 1.862377537130613, 1.641575868995102, 1.7998286592461676, 1.6984969286249811, 1.9156926693041125, 2.096887018596854, 1.4051212748562953, 5.252671229303795, 1.8811664685635334, 1.2947742309715304, 1.8460821693521077, 2.326048562125275, 1.2868414665169567, 1.74876404687841, 1.4669467258201363, 1.8530689474439233, 1.7882210652443449, 1.6942310061699601, 1.9624832478106176, 1.9601436965699424, 1.528229772161661, 1.3470647659122168, 1.6015818067328853, 2.0039022233001313, 1.6270251059729157, 1.1600530308767587, 1.9191506071294757, 2.183202831280071, 1.8040654336472806, 1.9987388522423337, 1.1629203268049602, 1.5348914648272494, 2.023855450422643, 1.4272455514533096, 3.1527502017235274, 1.674261587143643, 1.6586839131954887, 1.1339837108236481, 1.4428181511230616, 1.484052839177545, 1.6187228361587653, 0.9082824043878505, 1.4742820219740007, 1.2928780066611965, 1.7105080906995944, 1.8302660438584635, 1.6479379121534763, 1.2026275327598526, 0.9863727527305115, 2.0443151040153302]

In [19]:
k2 = zip(list(code.keys()), sector_variationlist)

a = pd.DataFrame(k2, columns=['기업명', '변동%평균'])


k3 = zip(name_list, kospi_variationlist)

b = pd.DataFrame(k3, columns=['기업명', '변동%평균'])

In [20]:
a.sort_values(by='변동%평균', ascending=False)

         기업명     변동%평균
0       하나제약  4.960817
12     파인디엔씨  2.922316
5     인텔리인테크  2.835841
4       큐캐피탈  2.612798
15      특수건설  2.595920
17    토박스코리아  2.318943
2   크라운해태홀딩스  2.258862
1       피델릭스  2.128648
6       진양화학  2.087965
9        파세코  1.880842
13      성광벤드  1.795095
16      하이트론  1.771374
7       평화정공  1.692510
14      티엘아이  1.572093
10     피제이메탈  1.471286
11      하이텍팜  1.382917
8        지투알  1.096438
3        퍼시스  0.693478

In [14]:
array1 = np.array(sector_variationlist) #섹터별 하나씩 17개
mean1 = array1.mean() #17개의 평균변동성의 평균

array2 = np.array(kospi_variationlist) #코스피 200 지수에 있는 200종목들 중 섹터별 엑셀파일에 있던 150여개의 기업 평균 변동성
mean2 = array2.mean() #150여개의 평균변동성의 평균

print(mean1, mean2)

2.1154524078264014 1.6909997031907225

In [15]:
a.sort_values(by='변동%평균', ascending=False)

            종목코드     변동%평균
하나제약      293480  4.960817
파인디엔씨     049120  2.922316
인텔리인테크    189300  2.835841
큐캐피탈      016600  2.612798
특수건설      026150  2.595920
토박스코리아    215480  2.318943
크라운해태홀딩스  005740  2.258862
피델릭스      032580  2.128648
진양화학      051630  2.087965
파세코       037070  1.880842
성광벤드      014620  1.795095
하이트론      019490  1.771374
평화정공      043370  1.692510
티엘아이      062860  1.572093
피제이메탈     128660  1.471286
하이텍팜      106190  1.382917
지투알       035000  1.096438
퍼시스       016800  0.693478